grid_map_topic: /grid_map_ploter_sensor1/grid_map
grid_map_visualizations:
  - name: sensor1_surface_normals
    type: vectors
    params:
      layer_prefix: normal_
      position_layer: elevation
      scale: 5
      line_width: 5
      color: 15600153 #
